export const DBBookData = [
  {
    id: "1",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publishedYear: 1960,
  },
  {
    id: "2",
    title: "Go Set a Watchman",
    author: "Harper Lee",
    publishedYear: 2015,
  },
  { id: "3", title: "1984", author: "George Orwell", publishedYear: 1949 },
  {
    id: "4",
    title: "Animal Farm",
    author: "George Orwell",
    publishedYear: 1945,
  },
  {
    id: "5",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publishedYear: 1813,
  },
  {
    id: "6",
    title: "Sense and Sensibility",
    author: "Jane Austen",
    publishedYear: 1811,
  },
  {
    id: "7",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publishedYear: 1925,
  },
  {
    id: "8",
    title: "This Side of Paradise",
    author: "F. Scott Fitzgerald",
    publishedYear: 1920,
  },
  {
    id: "9",
    title: "Moby-Dick",
    author: "Herman Melville",
    publishedYear: 1851,
  },
  {
    id: "10",
    title: "War and Peace",
    author: "Leo Tolstoy",
    publishedYear: 1869,
  },
  {
    id: "11",
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    publishedYear: 1877,
  },
  {
    id: "12",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publishedYear: 1951,
  },
  {
    id: "13",
    title: "Nine Stories",
    author: "J.D. Salinger",
    publishedYear: 1953,
  },
  {
    id: "14",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publishedYear: 1937,
  },
  {
    id: "15",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    publishedYear: 1954,
  },
  { id: "16", title: "Ulysses", author: "James Joyce", publishedYear: 1922 },
  { id: "17", title: "Dubliners", author: "James Joyce", publishedYear: 1914 },
  {
    id: "18",
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    publishedYear: 1880,
  },
  {
    id: "19",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    publishedYear: 1866,
  },
  {
    id: "20",
    title: "Brave New World",
    author: "Aldous Huxley",
    publishedYear: 1932,
  },
];
